{
 "title": "Ansible AWX",
 "description": "Ansible AWX dashboard valid for ansible tower also",
 "tags": [
  "pulse-line",
  "ansible",
  "awx",
  "tower"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Organizations Related",
   "type": "gauge",
   "description": "Total count of organizations, teams and users",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "awx_organizations_total", "legendFormat": "orgs" },
    { "expr": "awx_teams_total", "legendFormat": "teams" },
    { "expr": "awx_users_total", "legendFormat": "users" }
   ]
  },
  {
   "title": "Instance Info",
   "type": "table",
   "description": "Info about each node in a Tower system",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "awx_instance_info" },
    {
     "expr": "sum(awx_instance_cpu) by (hostname)"
    },
    {
     "expr": "sum(awx_instance_memory) by (hostname)"
    }
   ]
  },
  {
   "title": "Resources Total",
   "type": "table",
   "description": "Total count of projects, inventories",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "sum(awx_projects_total)" },
    { "expr": "sum(awx_inventories_total)" },
    {
     "expr": "sum(awx_inventory_scripts_total)"
    },
    {
     "expr": "sum(awx_workflow_job_templates_total)"
    },
    { "expr": "sum(awx_job_templates_total)" },
    { "expr": "sum(awx_schedules_total)" }
   ]
  },
  {
   "title": "Hosts Total",
   "type": "grafana-piechart-panel",
   "description": "Total count of hosts",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "awx_hosts_total{type=\"all\"}-ignoring(type)awx_hosts_total{type=\"active\"}",
     "legendFormat": "inactive"
    },
    {
     "expr": "awx_hosts_total{type=\"active\"}",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Hosts Total",
   "type": "graph",
   "description": "Total count of hosts",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "awx_hosts_total{type=\"all\"}-ignoring(type)awx_hosts_total{type=\"active\"}",
     "legendFormat": "inactive"
    },
    {
     "expr": "awx_hosts_total{type=\"active\"}",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "description": "Number of sessions",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "awx_sessions_total", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "virtual envs",
   "type": "graph",
   "description": "Number of virtualenvs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "awx_custom_virtualenvs_total", "legendFormat": "envs" }
   ]
  },
  {
   "title": "ongoing jobs",
   "type": "graph",
   "description": "Number of running and pending jobs on the AWX system",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "awx_running_jobs_total", "legendFormat": "running" },
    { "expr": "awx_pending_jobs_total", "legendFormat": "pending" }
   ]
  },
  {
   "title": "finished  jobs",
   "type": "grafana-piechart-panel",
   "description": "Status of Job launched",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 67 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "awx_status_total", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "finished  jobs",
   "type": "graph",
   "description": "Status of Job launched",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "awx_status_total", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "finished  jobs except project sync",
   "type": "grafana-piechart-panel",
   "description": "Status of Job launched",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 79 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "awx_instance_status_total", "legendFormat": "{{status}} - {{node}}" }
   ]
  },
  {
   "title": "finished  jobs except project sync",
   "type": "graph",
   "description": "Status of Job launched",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "awx_instance_status_total", "legendFormat": "{{status}} - {{node}}" }
   ]
  },
  {
   "title": "launch types",
   "type": "grafana-piechart-panel",
   "description": "Type of Job launched",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 91 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "awx_instance_launch_type_total", "legendFormat": "{{launch_type}}" }
   ]
  },
  {
   "title": "launch types",
   "type": "graph",
   "description": "Type of Job launched",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "awx_instance_launch_type_total", "legendFormat": "{{launch_type}}" }
   ]
  },
  {
   "title": "Resources Total",
   "type": "table",
   "description": "Total count of projects, inventories",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "sum(awx_instance_consumed_capacity) by (hostname)"
    },
    {
     "expr": "sum(awx_instance_remaining_capacity) by (hostname)"
    }
   ]
  },
  {
   "title": "Consumed",
   "type": "graph",
   "description": "Consumed capacity of each node in a Tower system",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "awx_instance_consumed_capacity", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Remaining",
   "type": "graph",
   "description": "Consumed capacity of each node in a Tower system",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "awx_instance_remaining_capacity",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}